
/*시퀀스 삭제*/
DROP SEQUENCE BOARD_SEQ;

/*테이블 삭제*/
DROP TABLE BOARD;

/*시퀀스 생성*/
CREATE SEQUENCE BOARD_SEQ;

/*테이블 생성*/
CREATE TABLE BOARD(
	BOARD_SEQ NUMBER NOT NULL,
	MEMBER_SEQ NUMBER NOT NULL,
	BOARD_CATEGORY VARCHAR2(10) NOT NULL,
	BOARD_TITLE VARCHAR2(500) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_IMG1 VARCHAR2(500),
	BOARD_IMG2 VARCHAR2(500),
	BOARD_DATE DATE NOT NULL,
	BOARD_COUNT NUMBER DEFAULT 0 NOT NULL,

	CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_SEQ),
	CONSTRAINT FK_BOARD_MEMBER_SEQ FOREIGN KEY(MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)
);

ALTER TABLE BOARD ADD (ISREAD VARCHAR2(2));
ALTER TABLE BOARD
MODIFY ISREAD CONSTRAINT ISREAD_NN NOT NULL;

/*제약조건 삭제*/
ALTER TABLE BOARD DROP CONSTRAINT MEMBER_SEQ_FK;

/*제약조건 추가*/
ALTER TABLE BOARD ADD CONSTRAINT MEMBER_SEQ_FK FOREIGN KEY (MEMBER_SEQ)
REFERENCES MEMBER(MEMBER_SEQ);

/*더미 INSERT*/
INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL, (SELECT MEMBER_SEQ FROM MEMBER WHERE MEMBER_SEQ = 1), 
'정치', '테스트', '테스트 내용', NULL, NULL, SYSDATE, DEFAULT)

/*SELECT 구문*/
SELECT * FROM BOARD ORDER BY BOARD_SEQ DESC;

SELECT A.* FROM
		(SELECT B.*, ROWNUM AS RNUM FROM(SELECT *
		FROM BOARD
		ORDER BY BOARD_SEQ DESC)B)A
		WHERE RNUM BETWEEN 11
		AND 20;

		SELECT COUNT(*)
		FROM BOARD_FAV 
		WHERE BOARD_SEQ = 5 AND MEMBER_SEQ = 1 AND BOARD_FAV_CHECK = 'Y';


		SELECT *
		FROM
		(SELECT A.*FROM
		(SELECT B.*, ROWNUM AS RNUM FROM (SELECT * FROM BOARD ORDER BY BOARD_SEQ
		DESC)B)A
		WHERE RNUM BETWEEN 1 AND 5)
		JOIN MEMBER USING (MEMBER_SEQ)
		ORDER BY BOARD_SEQ DESC
