CREATE SEQUENCE CHAT_SEQ;

CREATE TABLE CHAT (
	CHAT_SEQ NUMBER NOT NULL,
	CHAT_NAME VARCHAR2(500) NOT NULL,
	CHAT_CATEGORY VARCHAR2(10) NOT NULL,
	CHAT_MAKEDAY DATE NOT NULL,

	CONSTRAINT CHAT_SEQ_PK PRIMARY KEY(CHAT_SEQ)
)

INSERT INTO CHAT VALUES(CHAT_SEQ.NEXTVAL, '채팅방 이름', '기타', SYSDATE)

SELECT * FROM CHAT

CREATE SEQUENCE MESSAGE_SEQ;
CREATE TABLE MESSAGE (
	MESSAGE_SEQ NUMBER PRIMARY KEY,
	
	CHAT_SEQ NUMBER REFERENCES CHAT(CHAT_SEQ) NOT NULL,
	MEMBER_SEQ NUMBER REFERENCES MEMBER(MEMBER_SEQ) NOT NULL,
	MESSAGE_CONTENT VARCHAR2(500) NOT NULL,
	MESSAGE_TIME DATE NOT NULL,
	MESSAGE_REPORT NUMBER NOT NULL
);

SELECT * FROM MESSAGE

INSERT INTO MESSAGE VALUES(MESSAGE_SEQ.NEXTVAL, 1, 1, '테스트 메시지', SYSDATE, 0)
