--게시판 즐겨찾기
DROP SEQUENCE BOARD_FAV_SEQ; 
DROP TABLE BOARD_FAV;

CREATE SEQUENCE BOARD_FAV_SEQ;
CREATE TABLE BOARD_FAV(
	MEMBER_SEQ NUMBER NOT NULL,									--회원번호(FK)
	BOARD_SEQ NUMBER NOT NULL,									--게시판번호(FK)
	BOARD_FAV_SEQ NUMBER NOT NULL,
	BOARD_FAV_CHECK VARCHAR2(2) NOT NULL DEFAULT 'Y',			--즐겨찾기 여부
	
	CONSTRAINT PK_BOARD_FAV PRIMARY KEY(MEMBER_SEQ, BOARD_SEQ),	--복합키 지정
	CONSTRAINT FK_MEMBER_SEQ_LIKE FOREIGN KEY(MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ),
	CONSTRAINT FK_BOARD_SEQ_LIKE FOREIGN KEY(BOARD_SEQ) REFERENCES BOARD(BOARD_SEQ) ON DELETE CASCADE
);

--의안 즐겨찾기
DROP SEQEUNCE BILL_FAV_SEQ;
DROP TABLE BILL_FAV;

CREATE SEQUENCE BILL_FAV_SEQ;
CREATE TABLE BILL_FAV(
	MEMBER_SEQ NUMBER NOT NULL,									--회원번호
	BILL_ID VARCHAR2(40) NOT NULL,
	BILL_FAV_SEQ NUMBER NOT NULL,
	BILL_FAV_CHECK VARCHAR2(2) NOT NULL DEFAULT 'Y',			-- 즐겨찾기 여부
	
	CONSTRAINT PK_BILL_FAV PRIMARY KEY(MEMBER_SEQ, BILL_ID), 	-- 복합키 지정
	CONSTRAINT FK_MEMBER_SEQ_BILL FOREIGN KEY(MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ),
	CONSTRAINT FK_BILL_ID_LIKE FOREIGN KEY(BILL_ID) REFERENCES BILL(BILL_ID) ON DELETE CASCADE
);
