DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ;
ALTER TABLE MEMBER MODIFY(MEMBER_PW VARCHAR2(100));
CREATE TABLE MEMBER (
	MEMBER_SEQ NUMBER NOT NULL,
	MEMBER_ID VARCHAR2(20) NOT NULL,
	MEMBER_PW VARCHAR2(20) NOT NULL,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_EMAIL VARCHAR2(50) NOT NULL,
	MEMBER_SNS VARCHAR2(7) NOT NULL,
	MEMBER_ENABLE VARCHAR2(8) DEFAULT 'enabled',
	
	-- 관리자만 'Y'
	MEMBER_ROLE VARCHAR2(2) DEFAULT 'N',
	
	CONSTRAINT MEMBER_SEQ_PK PRIMARY KEY(MEMBER_SEQ),
	CONSTRAINT MEMBER_ENABLE_CK CHECK(MEMBER_ENABLE IN('enabled','block','disabled')),
	CONSTRAINT MEMBER_ROLE_CK CHECK(MEMBER_ROLE IN ('Y', 'N')),
	
	CONSTRAINT MEMBER_ID_UQ UNIQUE(MEMBER_ID),
	CONSTRAINT MEMBER_EMAIL_UQ UNIQUE(MEMBER_EMAIL)
);

INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'admin', 'admin1234', '관리자', 'admin@admin.com', 'general', 'enabled', 'Y');

SELECT * FROM MEMBER WHERE MEMBER_SEQ = 62;

UPDATE MEMBER SET MEMBER_ENABLE = 'enabled';
