DROP SEQUENCE REPLY_SEQ;
DROP TABLE REPLY;

CREATE SEQUENCE REPLY_SEQ;
CREATE TABLE REPLY(
	REPLY_SEQ NUMBER NOT NULL,
	BOARD_SEQ NUMBER NOT NULL,
	MEMBER_SEQ NUMBER NOT NULL,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	REPLY_DATE DATE NOT NULL,
	
	CONSTRAINT PK_REPLY PRIMARY KEY(REPLY_SEQ),
	CONSTRAINT FK_BOARD_SEQ FOREIGN KEY(BOARD_SEQ) REFERENCES BOARD(BOARD_SEQ) ON DELETE CASCADE,
	CONSTRAINT FK_MEMBER_REPLY_SEQ FOREIGN KEY(MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ) 
);

SELECT COUNT(R.REPLY_SEQ)
FROM REPLY R, BOARD B
WHERE R.BOARD_SEQ = B.BOARD_SEQ AND B.MEMBER_SEQ = 1 AND R.REPLY_ISREAD = 'N';

-- 댓글 읽음 표시 유무
ALTER TABLE REPLY ADD (REPLY_ISREAD VARCHAR2(2));
ALTER TABLE REPLY
MODIFY REPLY_ISREAD CONSTRAINT REPLY_ISREAD_NN NOT NULL;

ALTER TABLE REPLY DROP CONSTRAINT BOARD_SEQ_FK;
ALTER TABLE REPLY DROP CONSTRAINT MEMBER_SEQ_FK_2;

ALTER TABLE REPLY ADD CONSTRAINT BOARD_SEQ_FK FOREIGN KEY (BOARD_SEQ)
REFERENCES BOARD(BOARD_SEQ) ON DELETE CASCADE;

ALTER TABLE REPLY ADD CONSTRAINT MEMBER_SEQ_FK_2 FOREIGN KEY (MEMBER_SEQ)
REFERENCES MEMBER(MEMBER_SEQ);

INSERT INTO REPLY VALUES (REPLY_SEQ.NEXTVAL, (SELECT BOARD_SEQ FROM BOARD WHERE BOARD_SEQ = 1), 
(SELECT MEMBER_SEQ FROM MEMBER WHERE MEMBER_SEQ = 1), '테스트 댓글', SYSDATE)

-- 댓글 확인 후 읽음표시로 전환(하나)
UPDATE
(
SELECT 
*
FROM REPLY JOIN BOARD
USING (BOARD_SEQ)
WHERE BOARD.MEMBER_SEQ = 1 AND BOARD_SEQ = 27
) A
SET
A.REPLY_ISREAD = 'N';

		INSERT INTO REPLY VALUES
		(REPLY_SEQ.NEXTVAL, 44, 41,
		'안녕', SYSDATE, 'N');

SELECT * FROM REPLY ORDER BY REPLY_SEQ DESC;
